shell = "/usr/bin/zsh"

import = [
"~/.config/alacritty/catppuccin/catppuccin-mocha.toml",
"~/.config/alacritty/font.toml",
]

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
decorations = "None"
title = "Terminal"
resize_increments = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[cursor]
blink_interval = 500
[cursor.style]
shape = "Block"
blinking = "On"
[cursor.vi_mode_style]
shape = "Block"
blinking = "Never"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
