
[font]
size = 16
offset.x = 0
offset.y = 0
[font.normal]
style = "Light"
family = "JuliaMono Nerd Font"
[font.bold]
style = "Bold"
family = "JuliaMono Nerd Font"
[font.italic]
style = "MediumItalic"
family = "JuliaMono Nerd Font"
[font.bold_italic]
style = "BoldItalic"
family = "JuliaMono Nerd Font"
