
[font]
size = 16
offset.x = 0
offset.y = 0
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "MediumItalic"
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "BoldItalic"
