
[font]
size = 16
offset.x = 0
offset.y = 0
[font.normal]
style = "Medium"
family = "JuliaMono"
[font.bold]
family = "JuliaMono"
style = "Bold"
[font.italic]
family = "JuliaMono"
style = "MediumItalic"
[font.bold_italic]
family = "JuliaMono"
style = "BoldItalic"
