
[font]
size = 16
offset.x = 0
offset.y = 0
[font.normal]
style = "Medium"
family = "Mononoki Nerd Font"
[font.bold]
style = "Bold"
family = "Mononoki Nerd Font"
[font.italic]
style = "MediumItalic"
family = "Mononoki Nerd Font"
[font.bold_italic]
style = "BoldItalic"
family = "Mononoki Nerd Font"
