#! /bin/sh

/usr/libexec/polkit-gnome-authentication-agent-1 &
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
picom &
polybar top_primary &
dunst &
pgrep -x sxhkd > /dev/null || sxhkd &

xsetroot -cursor_name left_ptr  # set default cursor to be pointer
xinput set-prop 12 328 1        # enable "tapping" on trackpad

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config normal_border_color \#313244
bspc config active_border_color \#313244
bspc config focused_border_color \#cba6f7
bspc config presel_feedback_color \#89b4fa
bspc config urgent_border_color \#f38ba8

bspc config border_width         3
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a abtop state=floating rectangle=1536x864+192+108
bspc rule -a arandr state=floating rectangle=1536x864+192+108
