#!/bin/sh

# --- Setup --- #

/usr/libexec/polkit-gnome-authentication-agent-1 &
picom & 
dunst &
polybar minimal &
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
pgrep -x sxhkd > /dev/null || sxhkd &

xinput --set-prop "ELAN061B:00 04F3:309E Touchpad" "libinput Tapping Enabled" 1
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X

# --- Configuration --- #

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config focus_follows_pointer true

bspc config normal_border_color \#313244
bspc config active_border_color \#313244
bspc config focused_border_color \#cba6f7
bspc config presel_feedback_color \#89b4fa
bspc config urgent_border_color \#f38ba8

bspc config border_width         4
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# --- Window Rules --- #

bspc rule -a abtop state=floating rectangle=1536x864+192+108
bspc rule -a arandr state=floating rectangle=1536x864+192+108

bspc rule -a bspScratchTerm1 state=floating sticky=on layer=above rectangle=640x360+7+689
bspc rule -a bspScratchTerm2 state=floating sticky=on layer=above rectangle=640x360+7+7
bspc rule -a bspScratchTerm3 state=floating sticky=on layer=above rectangle=640x360+1273+689
bspc rule -a bspScratchTerm4 state=floating sticky=on layer=above rectangle=640x360+1273+7
