[window]
width = 600
height = 600
anchor = "center"
margin_top = 0
margin_bottom = 0
margin_left = 0
margin_right = 0
show_descriptions = false
show_paths = false
show_icons = true
show_search = true
show_actions = false
show_border = true
border_width = 2
use_gtk_colors = false
use_custom_css = false
max_entries = 50

[window.custom_navigate_keys]
up = "k"
down = "j"
delete_word = "h"

[theme.colors]
border = "#cba6f7"
item_bg = "#181825"
item_bg_hover = "#1e1e2e"
item_bg_selected = "#1e1e2e"
item_description = "#313244"
item_description_selected = "#a0a0a0"
item_name = "#cdd6f4"
item_name_selected = "#ffffff"
item_path = "#bac2de"
item_path_selected = "#808080"
search_bg = "#181825"
search_bg_focused = "#1e1e2e"
search_caret = "#bac2de"
search_text = "#cdd6f4"
window_bg = "#11111b"

[theme.corners]
window = 14
search = 9
list_item = 9

[theme.spacing]
search_margin = 12
search_padding = 12
item_margin = 6
item_padding = 4

[theme.typography]
search_font_size = 16
item_name_size = 14
item_description_size = 12
item_path_size = 12
item_path_font_family = "monospace"

[debug]
disable_auto_focus = false
enable_logging = false

[calculator]
enabled = false

[dmenu]
allow_invalid = false
case_sensitive = false

[web_search]
enabled = false
engine = "duckduckgo"
prefixes = []
