#!/usr/bin/python
import os, sys, errno

fonts_dir = "/home/benjamin/.config/alacritty/fonts/"
files = sorted(os.listdir(fonts_dir))
valid = lambda s: s.endswith(".toml")
exists = lambda s: str(s + ".toml") in files

if len(sys.argv) != 2:
    print("Usage:\n  font <fontname>\n")
    print("Available fonts:")
    print("\n".join(map(lambda s: "- " + s[:-5], filter(valid, files))))
    sys.exit(0)

font = sys.argv[1]
if not exists(font):
    print("Please provide a valid font.\n\nAvailable fonts:")
    print("\n".join(map(lambda s: "- " + s[:-5], filter(valid, files))))
    sys.exit(0)

import shutil

src = fonts_dir + font + ".toml"
dest = "/home/benjamin/.config/alacritty/font.toml"
try:
    shutil.copyfile(src, dest)
    print("Successfully changed font :)")
except Exception as e:
    print("Failed to change font :(")
    print(e)
