
[general]

import = [
"~/.config/alacritty/colors.toml",
]

# [terminal]
# shell = "/usr/bin/zsh"
[terminal.shell]
program = "tmux"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
decorations = "None"
title = "Terminal"
resize_increments = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[font]
size = 16
offset.x = 0
offset.y = 0
[font.normal]
style = "Light"
family = "JuliaMono Nerd Font"
[font.bold]
style = "Bold"
family = "JuliaMono Nerd Font"
[font.italic]
style = "MediumItalic"
family = "JuliaMono Nerd Font"
[font.bold_italic]
style = "BoldItalic"
family = "JuliaMono Nerd Font"

[cursor]
blink_interval = 500
[cursor.style]
shape = "Block"
blinking = "On"
[cursor.vi_mode_style]
shape = "Block"
blinking = "Never"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]
