#!/bin/bash

if [ -z "$WALLPAPERS" ]; then
    WALLPAPERS="$HOME/.local/share/backgrounds"
fi

currentwall=$(grep -o -e "$WALLPAPERS/.*[a-zA-Z]" ~/.fehbg | awk -F '/' '{print $NF}')
nextwall=$((ls $WALLPAPERS | grep -A1 $currentwall | (cat ; (ls $WALLPAPERS | head -n 1))) | sed '2q;d')
feh --bg-scale "$WALLPAPERS/$nextwall"

# Pretty much, I'm checking what the current wallpaper is,
# and then setting the "next one" in the directory to be the new wallpaper,
# looping around if we are at the last one.
